CREATE TABLE ACTOR (
	PersID INT NOT NULL auto_increment,
	Firstname VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	PlaceOfBirth VARCHAR(45),
	Birthdate DATE,
	Gender	CHAR NOT NULL,
	PRIMARY KEY (PersID));
	
CREATE TABLE DIRECTOR(
	PersID INT NOT NULL auto_increment,
	Firstname VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	PlaceOfBirth VARCHAR(45),
	Birthdate DATE,
	Gender	CHAR NOT NULL,
	PRIMARY KEY (PersID));

CREATE TABLE USER(
	Email VARCHAR(45) NOT NULL,
	Password VARCHAR(45) NOT NULL,
	Firstname VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	RegistrationDate TIMESTAMP NOT NULL,
	Birthdate DATE,
	Gender	CHAR ,
	PRIMARY KEY (Email));

CREATE TABLE STUDIO (
	StudioID INT NOT NULL auto_increment,
	Name VARCHAR(45) NOT NULL,
	Headquarter VARCHAR(45),

	PRIMARY KEY (StudioID));

CREATE TABLE MOVIE (
	MovieID INT NOT NULL auto_increment,
	Title VARCHAR(45) NOT NULL,
	ReleaseDate DATE,
	Genre VARCHAR(45),
	Mood VARCHAR(45),
	Duration INT NOT NULL,
	AvgRating INT,
	RatingCount INT,
	AgeRating INT NOT NULL,
	D_PersID INT NOT NULL,
	StudioID INT,

	PRIMARY KEY (MovieID),
	CONSTRAINT directs FOREIGN KEY (D_PersID)
	REFERENCES DIRECTOR (PersID)
	ON DELETE RESTRICT);
	
CREATE TABLE ACTSIN (
	A_PersID INT NOT NULL,
	M_MovieID INT NOT NULL,

	PRIMARY KEY (A_PersID,M_MovieID),

	CONSTRAINT a_acts FOREIGN KEY (A_PersID)
	REFERENCES ACTOR (PersID)
	ON DELETE CASCADE,

	CONSTRAINT m_acts FOREIGN KEY (M_MovieID)
	REFERENCES MOVIE (MOVIEID)
	ON DELETE CASCADE);

CREATE TABLE WATCHLIST (
	U_Email VARCHAR(45) NOT NULL,
	M_MovieID INT NOT NULL,
	Seen BOOLEAN NOT NULL,

	PRIMARY KEY (U_Email,M_MovieID),

	CONSTRAINT u_watches FOREIGN KEY (U_Email)
	REFERENCES USER (Email)
	ON DELETE CASCADE,

	CONSTRAINT m_watches FOREIGN KEY (M_MovieID)
	REFERENCES MOVIE (MovieID)
	ON DELETE CASCADE);

CREATE TABLE COMMENT (
	CommentID INT NOT NULL auto_increment,
	Text TEXT NOT NULL,
	Date DATE NOT NULL,
	Time TIME NOT NULL,
	Position TIME,
	M_MovieID INT NOT NULL,
	U_Email VARCHAR(45),

	PRIMARY KEY (CommentID),
	
	CONSTRAINT u_comments FOREIGN KEY (U_Email)
	REFERENCES USER (Email)
	ON DELETE SET NULL,

	CONSTRAINT m_comments FOREIGN KEY (M_MovieID)
	REFERENCES MOVIE (MovieID)
	ON DELETE CASCADE);
	

